### ISSUE TITLE
No module scripts found

### ISSUE THREAD

**Issue by xhamudx** [restrepo/inspireauth#2]
When running the notebook "test_generate_dataframe.ipynb" in the release branch, I got "NotModuleFoundError: No module named `'scripts'." 
![WhatsApp Image 2024-09-10 at 08 08 10](https://github.com/user-attachments/assets/1e67f1c5-3bf6-49f0-a2e0-cf10da0e2cfe)

**Comment by manuel-morales-a** [comment]
Fixed! Thanks for reporting it Mario. Pull now to confirm that it works please!
